Arithmetic
KKuzmane/c-sharp-tasks-Kristine pull request #2
Opened 2021-11-26 16:57 UTC by KKuzmane

All arithmetic tasks

2021-11-27 14:18 UTC, ausmoons requested changes

2021-11-27 14:18 UTC, ausmoons commented on c-sharp-syllabus-main/c-sharp-syllabus-main/csharp-basics/exercises/Arithmetic/BMI/Program.cs
> +                Console.WriteLine("Your BMI is " + BMI + ". You are optimal weight");
Kur būs 18.5 un 25?

2021-11-27 14:18 UTC, ausmoons commented on c-sharp-syllabus-main/c-sharp-syllabus-main/csharp-basics/exercises/Arithmetic/CalculateArea/Geometry.cs
> +            //throw new NotImplementedException();
Lieks komentārs

2021-11-27 14:18 UTC, ausmoons commented on c-sharp-syllabus-main/c-sharp-syllabus-main/csharp-basics/exercises/Arithmetic/CozaLozaWoza/Program.cs
> +                        {
Te kkas nav ar {

2021-11-27 14:18 UTC, ausmoons commented on c-sharp-syllabus-main/c-sharp-syllabus-main/csharp-basics/exercises/Arithmetic/CozaLozaWoza/Program.cs
> +                    {
Number vietā būtu jālieto i

2021-11-27 14:18 UTC, ausmoons commented on c-sharp-syllabus-main/c-sharp-syllabus-main/csharp-basics/exercises/Arithmetic/SumAverageRunningInt/Program.cs
> +
Liek tukša rinda

2021-11-27 21:25 UTC, EdgarsSalmins commented on c-sharp-syllabus-main/c-sharp-syllabus-main/csharp-basics/exercises/Arithmetic/CalculateArea/Geometry.cs
> +            //throw new NotImplementedException();
jānodzēš. :) šitais lieks.

2021-11-28 20:40 UTC, ausmoons requested changes

2021-11-28 20:40 UTC, ausmoons commented on c-sharp-syllabus-main/c-sharp-syllabus-main/csharp-basics/exercises/Arithmetic/BMI/Program.cs
> +            double optimalBMIMin = 18.5;
Izskatās pēc lieka komentāra

2021-11-29 10:00 UTC, ausmoons approved these changes

2021-11-29 11:32 UTC, merged