Collections
KKuzmane/c-sharp-tasks-Kristine pull request #7
Opened 2021-12-17 19:33 UTC by KKuzmane

Collections finished

2021-12-19 20:43 UTC, ausmoons requested changes

2021-12-19 20:43 UTC, ausmoons commented on c-sharp-syllabus-main/c-sharp-syllabus-main/csharp-basics/exercises/Collections/Exercise 3/Program.cs
> +            List<string> names = new List<string>();
Kāpēc ne hashset?

2021-12-19 20:43 UTC, ausmoons commented on c-sharp-syllabus-main/c-sharp-syllabus-main/csharp-basics/exercises/Collections/Phonebook/PhoneDirectory.cs
> +            if (_data.ContainsKey(name))
return _data.ContainsKey(name)

2021-12-19 20:43 UTC, ausmoons commented on c-sharp-syllabus-main/c-sharp-syllabus-main/csharp-basics/exercises/Collections/Phonebook/PhoneDirectory.cs
> +        private bool Find(string name) {
{ jaunā rindā

2021-12-19 20:43 UTC, ausmoons commented on c-sharp-syllabus-main/c-sharp-syllabus-main/csharp-basics/exercises/Collections/Exercise 3/Program.cs
> +            foreach(string word in uniqueNames)
Kurā brīdī tiešām te ir tikai unique names?

2021-12-20 08:31 UTC, KKuzmane commented on c-sharp-syllabus-main/c-sharp-syllabus-main/csharp-basics/exercises/Collections/Exercise 3/Program.cs
> +            foreach(string word in uniqueNames)
Vai 25.rindā ar Distinct tas netiek noteikts? Testēju un man atgrieza tikai unique names.

2021-12-20 08:32 UTC, KKuzmane commented on c-sharp-syllabus-main/c-sharp-syllabus-main/csharp-basics/exercises/Collections/Exercise 3/Program.cs
> +            List<string> names = new List<string>();
Tāpēc, ka tas bija viens no pirmajiem uzdevumiem un šajā brīdī man tas likās piemērotāks. Kāpēc neder List?

2021-12-20 20:07 UTC, ausmoons approved these changes

2021-12-20 20:07 UTC, ausmoons commented on c-sharp-syllabus-main/c-sharp-syllabus-main/csharp-basics/exercises/Collections/Exercise 3/Program.cs
> +            List<string> names = new List<string>();
Jo pēc tam jāveic vēl viena darbība, lai būtu unique

2021-12-21 10:26 UTC, merged